language: java
stages:
- test
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: test
    script: "./gradlew check"
  - stage: deploy
    script: "./gradlew distZip cf-push -Pcf.ccUser=${CF_USER} -Pcf.ccPassword=${CF_PASSWORD}"
